In [1]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [3]:
#Auto grad example
x=torch.tensor(1.0,requires_grad=True)
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(1.0,requires_grad=True)

#Build the graph
y = w*(x**2)+b*x

#calculate gradients
y.backward()

#print gradients
print(x.grad,w.grad,b.grad)


tensor(5.) tensor(1.) tensor(1.)


In [38]:
#Simple neural network
x = torch.randn(1000,2)
w = torch.tensor([3.0,4.0])
w = w.reshape(2,1)
y = torch.mm(x,w)
print(x.shape,y.shape,w.shape)
net = nn.Linear(2,1)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
#check initial weights
print("W: {}, b: {}".format(net.weight,net.bias))

#forward pass
def forward(x):
    prediction = net(x)
    loss = criterion(prediction,y)
    return loss

def train(steps = 1000):
    alpha = 0.1
    for i in range(steps):
        loss = forward(x)
        loss.backward()
        #do gradient descent
        net.weight.data.sub_(alpha * net.weight.grad.data)
        net.bias.data.sub_(alpha * net.bias.grad.data)
        if i%100==0:
            alpha*=0.5
        #print gradients
#         print("dL/dW = {} and dL/dB = {}".format(net.weight.grad, net.bias.grad))
#         optimizer.step()
    print("W: {}, b: {}".format(net.weight,net.bias))
train(1000)



torch.Size([1000, 2]) torch.Size([1000, 1]) torch.Size([2, 1])
W: Parameter containing:
tensor([[-0.6647, -0.6871]], requires_grad=True), b: Parameter containing:
tensor([-0.5664], requires_grad=True)
W: Parameter containing:
tensor([[3.0228, 3.8815]], requires_grad=True), b: Parameter containing:
tensor([1.0506], requires_grad=True)


In [ ]:
#Loading numpy data


In [61]:
#making discriminator
class Discriminator(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(Discriminator, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
#         self.first_layer = torch.randn(input_size[2],1, input_size[0])
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        # Forward propagate LSTM
#         out = torch.mm(x,self.first_layer)
#         print(out.shape)
        out, _ = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time step
        out = self.fc(out[:, -1, :])
        return out
    def train()

In [62]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
D = Discriminator(4,10,1,1).to(device)

In [64]:
x = torch.randn(10,10,4)
print(D.forward(x))

tensor([[-0.1596],
        [-0.1747],
        [-0.1989],
        [-0.0826],
        [-0.2304],
        [-0.2050],
        [-0.1999],
        [-0.1366],
        [-0.0909],
        [-0.2130]], grad_fn=<ThAddmmBackward>)


In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(D.parameters(), lr=learning_rate)
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))
